# general configuration
:extended_iterations: 40

# additional user-defined (fully qualified) directories
:dirs:
  :workloads: c:/workloads
  #:logs: c:/logs

# API tracer configuration
:tracer:
  -
    :name: ProcessMonitor
    :active: true
    :exe: C:/winsystools/ProcessMonitor/procmon.exe
  -
    :name: APIMonitor
    :active: false
    :exe: c:/winsystools/APIMonitor/apimonitor-x86.exe

# Profiler configuration
:profiler:
  -
    :name: AmplifierXE
    :active: true
    :exe: C:/Program Files/Intel/VTune Amplifier XE 2011/bin32/amplxe-cl.exe

# Benchmarking configuration
:bench:
  :iterations: 3
